checks:
    php: true
build:
    environment:
        php:
            version: 5.6
            ini:
                'date.timezone': 'America/Sao_Paulo'
filter:
    excluded_paths:
        - tests/*
tools:
    external_code_coverage: true
